version: '3.8'
services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '${NGINX_PORT}:80'
  nginx:
    build:
      context: ./project/docker/development/nginx
    volumes:
      - ./project:/app
    environment:
      VIRTUAL_HOST: ${NGINX_VIRTUAL_HOST}
    depends_on:
      - proxy
      - php-fpm
  php-fpm:
    build:
      context: ./project/docker/development/php-fpm
    volumes:
      - ./project:/app
    depends_on:
      - db
  php-cli:
    build:
      context: ./project/docker/development/php-cli
    volumes:
      - ./project:/app
      - composer:/root/.composer/cache
    depends_on:
      - db
  db:
    image: mysql/mysql-server:8.0
    ports:
      - '${DB_PORT}:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./data/mysql:/var/lib/mysql
#  db:
#    image: postgres:14.2-alpine
#    volumes:
#      - ./data/postgresql:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_DATABASE}
#    ports:
#      - '${DB_PORT}:5432'
volumes:
  composer: